---
# tasks file for repo-zabbix

- name: Install Zabbix repo
  package:
    name: "{{ zabbix_repo_package_url }}"
    state: preset
  register: result
  until: 'result.rc == 0'
  retries: 5
  delay: 10

- name: Import Zabbix GPG key
  rpm_key:
    key: "{{ zabbix_repo_gpg_key_url }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  when: ansible_os_family == "RedHat"


- name: Import Zabbix GPG key
  apt_key:
    key: "{{ zabbix_repo_apt_key_url }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: test

